name: Build ESP8266 Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Cache Arduino CLI
      uses: actions/cache@v4
      with:
        path: |
          ~/.arduino15
          ~/Arduino/libraries
        key: ${{ runner.os }}-arduino-${{ hashFiles('**/ESP8266_WebServer_Timer.ino') }}
        restore-keys: |
          ${{ runner.os }}-arduino-
          
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1
      
    - name: Install ESP8266 platform
      run: |
        arduino-cli core update-index --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
        arduino-cli core install esp8266:esp8266 --additional-urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
      
    - name: List repository contents
      run: ls -R
      
    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp8266:esp8266:d1_mini ESP8266_WebServer_Timer.ino --output-dir ./
      
    - name: Rename output file
      run: |
        if [ -f ESP8266_WebServer_Timer.ino.bin ]; then
          mv ESP8266_WebServer_Timer.ino.bin firmware.bin
        else
          echo "Error: Compiled binary not found"
          exit 1
        fi
      
    - name: Upload firmware as artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware.bin

    - name: Display Arduino CLI version
      run: arduino-cli version
      
    - name: Display installed boards
      run: arduino-cli board listall
      
    - name: Display installed libraries
      run: arduino-cli lib list
      
