name: Build Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2.0.0
        with:
          version: '1.0.0'  # Specify the version you need
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add ESP8266 Board Manager
        run: |
          arduino-cli core update-index
          arduino-cli core install esp8266:esp8266
        env:
          ADDITIONAL_URLS: http://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Check arduino-cli Installation
        run: |
          echo "arduino-cli installation path:"
          which arduino-cli
          arduino-cli version

      - name: Compile firmware
        run: arduino-cli compile --fqbn esp8266:esp8266:d1_mini ESP8266_WebServer_Timer.ino

      - name: Upload firmware
        run: arduino-cli upload --fqbn esp8266:esp8266:d1_mini ESP8266_WebServer_Timer.ino
